---
vagrantfile-local:
    vm:
        box: centos-6.5
        box_url: https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box
        hostname: centos65
        domain: example.com
        memory: '512'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
        provision:
            puppet:
                manifests_path: puppet
                manifest_file: manifest.pp
                module_path: puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puppet/hiera.yaml'
                    - '--parser future'
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
    php:
        install: '1'
        version: '55'
        composer: 1
        modules:
            php:
                - cli
                - intl
                - mcrypt
            pear: {  }
            pecl:
                - pecl_http
        ini:
            display_errors: On
            error_reporting: '-1'
            session.save_path: /var/lib/php/session
        timezone: America/New York